name: Push Docker image

on:
  # push:
  #   branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker
      run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}

    - name: Build image
      run: docker build -t boreddevco/imsekun/fengen:0.1.0 .

    - name: Publish image
      run: docker push boreddevco/imsekun/fengen:0.1.0
